name: Build Plugin
on: [push, workflow_dispatch]
jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Add MSBuild to PATH
        uses: microsoft/setup-msbuild@v2

      - name: Download and Force-Place SDK
        run: |
          git clone --depth 1 https://github.com/bakkesmodorg/BakkesMod2-Plugins.git sdk_temp
          # Sadece gereken klasörü projenin tam içine kopyalıyoruz
          xcopy /E /I sdk_temp\bakkesmod bakkesmod
          # Derleyiciye bu yolu doğrudan tanıtalım
          echo "BAKKESMODSDK_PATH=$github_workspace" >> $GITHUB_ENV

      - name: Build Plugin
        run: msbuild BakkesPluginTemplate.vcxproj /p:Configuration=Release /p:Platform=x64 /p:AdditionalIncludeDirectories="$github_workspace"

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: SteamPFPs-Plugin
          path: |
             x64/Release/*.dll
             Release/*.dll
