name: Build Plugin
on: [push, workflow_dispatch]
jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Add MSBuild to PATH
        uses: microsoft/setup-msbuild@v2

      - name: Setup BakkesMod SDK
        run: |
          git clone --depth 1 https://github.com/bakkesmodorg/BakkesMod2-Plugins.git sdk_temp
          # SDK klasörünü projenin ana dizinine kopyalar
          xcopy /E /I sdk_temp\bakkesmod bakkesmod
          # Derleyiciye kütüphanelerin tam yerini söyler
          echo "BAKKESMOD_SDK_PATH=$github_workspace" >> $GITHUB_ENV

      - name: Build Plugin
        run: |
          msbuild BakkesPluginTemplate.vcxproj /p:Configuration=Release /p:Platform=x64 /p:IncludePath="$github_workspace;$github_workspace\bakkesmod\include;$(IncludePath)"
        
      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: SteamPFPs-Plugin
          path: |
            **/Release/*.dll
            x64/Release/*.dll
